"""add lamination_time to parts and create cure_cycles table

Revision ID: 7b0f1937b967
Revises: 455e264c6e0c
Create Date: 2025-05-11 12:50:35.582891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b0f1937b967'
down_revision: Union[str, None] = '455e264c6e0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cure_cycles',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_cure_cycles_code'), 'cure_cycles', ['code'], unique=False)
    op.add_column('parts', sa.Column('lamination_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parts', 'lamination_time')
    op.drop_index(op.f('ix_cure_cycles_code'), table_name='cure_cycles')
    op.drop_table('cure_cycles')
    # ### end Alembic commands ###
