"""add autoclave_supported_cycles table for N:M relation with CureCycle

Revision ID: ce4649da7371
Revises: 7b0f1937b967
Create Date: 2025-05-11 12:59:18.890946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce4649da7371'
down_revision: Union[str, None] = '7b0f1937b967'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autoclave_supported_cycles',
    sa.Column('autoclave_id', sa.Integer(), nullable=False),
    sa.Column('cycle_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['autoclave_id'], ['autoclaves.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cycle_code'], ['cure_cycles.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('autoclave_id', 'cycle_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('autoclave_supported_cycles')
    # ### end Alembic commands ###
